### PR TITLE
modernize rabbitmq

### PR DESCRIPTION
**Pull request by mattgiles**

### CODE REVIEW

**Comment by mgasner** [comment]
how has this been tested?

**Comment by mattgiles** [comment]
This has been tested in the dev cloud with

``` shell
ansible-playbook playbooks/schedule_services.yml --tags "dev,rabbitmq"
```

**Comment by mattgiles** [comment]
Has also been tested stand alone locally on my dev box.

**Comment by mattgiles** [comment]
Remaining test I want to run is running lemming test suite locally using this image.

**Comment by mattgiles** [comment]
screen shot 2016-02-01 at 1 10 22 pm

**Comment by mgasner** [comment]
i assume this cannot merge until some conditions are met -- please enumerate them

**Comment by mattgiles** [comment]
this cannot merge until we are prepared to migrate production cloud to swarm cluster using consul for service discovery.

**Comment by mgasner** [comment]
is there a concurrent PR in lemming to do some actual routing?

**Comment by mgasner** [comment]
see https://github.com/onefinancial/lemming/pull/438

**Pull request merged**
